GET  http://localhost:3000/subscribers

###
GET http://localhost:3000/subscribers/77
###
POST http://localhost:3000/subscribers
Content-Type:application/json

{
    "name":"Kdee",
    "channel":"Freecode camp",
}